version: "3.8"
services:

  redis:
    image: redis:alpine
    container_name: redis

  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=forum
      - POSTGRES_USER=forum_admin
      - POSTGRES_PASSWORD=forumadmin
      - POSTGRES_ENGINE=django.db.backends.postgresql
      - POSTGRES_PORT=5432
      
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: bash -c "gunicorn --bind 0.0.0.0:8000 forum.wsgi:application --reload & celery -A forum worker -l INFO"
    image: masood04/app
    expose:
      - 8000
    volumes:
      - ./src:/home/forum_admin/django-forum
      - staticfiles:/home/forum_admin/django-forum/staticfiles
    env_file:
      - ./.env

    container_name: forum_app

    environment:
      - POSTGRES_DB=forum
      - POSTGRES_USER=forum_admin
      - POSTGRES_PASSWORD=forumadmin
      - POSTGRES_ENGINE=django.db.backends.postgresql
      - POSTGRES_PORT=5432
      
  
    depends_on:
      - db
      - redis

  nginx:
    build: 
      context: ./
      dockerfile: ./nginx/Dockerfile
    
    image: masood04/forum_nginx:latest

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/var/www/staticfiles

    ports:
      - 80:80

    depends_on:
      - app

  # celery:
  #   restart: always
  #   build: 
  #     context: .
  #   image: masood04/celery

  #   command: celery -A forum worker -l INFO
    
  #   volumes:
  #     - ./src:/django-forum
  #   container_name: celery

  #   env_file:
  #     - ./.env
      
  #   depends_on:
  #     - db
  #     - redis
  #     - app

volumes:
  staticfiles:
  nginx.conf:
  postgres-data: