# Generated by Django 4.0.3 on 2022-06-25 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
    ]
