# Generated by Django 4.0.5 on 2022-07-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, default='default', unique=True),
            preserve_default=False,
        ),
    ]
