# Generated by Django 4.0.3 on 2022-06-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0003_alter_question_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='best_answer_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='is_best',
            field=models.BooleanField(default=False),
        ),
    ]
