# Generated by Django 4.0.2 on 2022-03-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0012_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='thread.Tag'),
        ),
    ]
