# Generated by Django 4.0.3 on 2022-04-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0014_alter_question_options_alter_answer_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
