# Generated by Django 4.0.3 on 2022-04-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0015_alter_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
