# Generated by Django 4.0.3 on 2022-04-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0017_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.IntegerField(choices=[(1, 'Up Vote'), (-1, 'Down Vote')]),
        ),
    ]
