# Generated by Django 4.0.3 on 2022-04-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0018_alter_vote_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.IntegerField(choices=[('Up Vote', 1), ('Down Vote', -1)]),
        ),
    ]
