# Generated by Django 4.0.3 on 2022-04-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0020_alter_vote_answer_alter_vote_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.IntegerField(choices=[(1, 'Up Vote')]),
        ),
    ]
